### ISSUE TITLE
[BUG] image creating logs in overlay filesystem

### ISSUE THREAD

**Issue by dkarlovi** [opensearch-project/docker-images#28]
### What is the bug?

Running the  image dumps logs into the filesystem

### How can one reproduce the bug?

Run this Docker Compose and run `docker diff`:

```yaml
services:
    store:
        image: opensearchproject/opensearch:2.7.0
        environment:
            - cluster.name=opensearch
            - node.name=opensearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - knn.memory.circuit_breaker.limit=10%
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - store:/usr/share/opensearch/data
        restart: unless-stopped
        tmpfs:
            - /tmp
```

### What is the expected behavior?

Logs are streamed to STDOUT / STDERR, no logs are added onto the filesystem.

### What is your host/environment?

Linux Fedora

### Do you have any screenshots?

No.

### Do you have any additional context?

`docker diff` shows what changes have been made to the container from the source image.
