### ISSUE TITLE
[BUG] high CPU usage, memory usage

### ISSUE THREAD

**Issue by dkarlovi** [opensearch-project/docker-images#29]
### What is the bug?

I get an endless stream of files matching `/tmp/sqlite-3.32.3.2-[UUID]-libsqlitejdbc.so`

### How can one reproduce the bug?

Start the service like this

```yaml
services:
    store:
        image: opensearchproject/opensearch:2.7.0
        environment:
            - cluster.name=opensearch
            - node.name=opensearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - knn.memory.circuit_breaker.limit=10%
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - store:/usr/share/opensearch/data
        restart: unless-stopped
        tmpfs:
            - /tmp
```

Since the /tmp is mounted as tmpfs, this consumes huge amounts of RAM and eventually the machine dies.

See this from within the container

```
sh-4.2$ date; ls -l /tmp/sqlite-3.32.3.2-*.so | wc -l
Mon May 29 14:01:40 UTC 2023
12270
sh-4.2$ date; ls -l /tmp/sqlite-3.32.3.2-*.so | wc -l
Mon May 29 14:01:43 UTC 2023
12335
sh-4.2$ date; ls -l /tmp/sqlite-3.32.3.2-*.so | wc -l
Mon May 29 14:01:45 UTC 2023
12372
```

### What is the expected behavior?

Download it once and use it successfully? Or not download it at all, it should be part of the image? Maybe downloading it works around some licensing?

### What is your host/environment?

Fedora Linux 38

```
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:42 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:08 2023
  OS/Arch:          linux/amd64
  Experimental:     false

 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Do you have any screenshots?

N/A.

### Do you have any additional context?

It might be related to performance analyzer since I'm noticing it's using a lot of CPU constantly, maybe that's what's doing it.
